[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ico"
  [headers.values]
    Content-Type = "image/vnd.microsoft.icon"
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"